### ISSUE TITLE
Feature: User can view the map and location of ski resorts

### ISSUE THREAD

**Issue by heesoo-kim97** [heesoo-kim97/Interactive-Map#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="608" alt="Screen Shot 2021-09-13 at 5 29 19 PM" src="https://user-images.githubusercontent.com/82424354/133174308-0b765409-79b4-45d2-b283-cd0b4be92b05.png">
<img width="214" alt="Screen Shot 2021-09-13 at 5 29 35 PM" src="https://user-images.githubusercontent.com/82424354/133174343-c8d03f4f-61c4-4a6e-b4bb-ccefe6a46565.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Create a component to handle markers based on resort's location
- [ ] Handle header - SKI XPLOR 
- [ ] Pull data from skimap api
- [ ] apply leaflet css for the marker
- [ ] apply style to the map
- [ ] media query to make it look nice in phone app

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
